dist: trusty
services:
    - docker
script:
    - docker build -t $REPO/$IMAGE_NAME .
    - echo "$TOKEN" | docker login  docker.pkg.github.com --username XiaolinGe --password-stdin
    - docker tag $REPO/$IMAGE_NAME:latest $REPO/$IMAGE_NAME:$TRAVIS_BUILD_NUMBER
    - docker push $REPO/$IMAGE_NAME:latest
    - docker push $REPO/$IMAGE_NAME:$TRAVIS_BUILD_NUMBER
env:
    global:
        - IMAGE_NAME=big-data-tool-mysql
        - REPO=docker.pkg.github.com/XiaolinGe/big-data-tool-mysql